name: 'Build vk-gl-cts for OpenGL'
on:
  push:

jobs:
  build-vk-gl-cts-opengl:
    name: Build VK GL CTS for OpenGL
    runs-on: [self-hosted, linux, ARM64, noble]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        shell: bash
        run: |
          sudo apt update -y
          sudo apt install -y build-essential cmake ocl-icd-libopencl1 libva2 libva-drm2 libpng-dev libboost-all-dev ninja-build clang ocl-icd-opencl-dev clinfo python3-pip meson glslang-tools pkg-config cmake libvulkan-dev libgl1 mesa-common-dev libglfw3-dev libgles2-mesa-dev wayland-protocols pip3 install opencv-python lxml --break-system-packages

      - name: Add prebuilt bootloader files
        shell: bash
        run: |
          git clone https://github.com/KhronosGroup/VK-GL-CTS
          cd VK-GL-CTS
          git checkout vulkan-cts-1.4.1.3
          python3 external/fetch_sources.py
          mkdir build && cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_FLAGS=-march=armv8-a -DCMAKE_CXX_FLAGS=-march=armv8-a
          # 64GB RAM wasn't enough for -j. Add nproc
          make -j`nproc`

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: |
            VK-GL-CTS/*
          name: vk-gl-cts
          retention-days: 7
